# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac647e62aa5b19ec9fc8380dccd3b7494f84ad3a40893d2cc352d4403598c2267b04c563dae941f23f3cc344319c920c0a8a8e91d6f5aea45ee23ca567d8f640

test:
  secret_key_base: e29fb6e548d259929b8f3b990702cfb65d6b1c479e3df065218959cf49079e58aff52000f61a100378aa040f3b3be5ea4251c5d66440a9eec3841e6798f83776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
