# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a2751bade63facc1293dabb1bbbf3d8c3ef177578e7d17c345f76922376519e6b7a338076ebe4996655c9afc3cbdc80ec9114094b520fdc4460a63780fb469

test:
  secret_key_base: 9927d23da5b9dca1fda10c805d41a40cdc20b9e3f70394aff545b100ade3adcf470ca25f9588afef0599b640e7bf8d2a0c92ae84b523770f3245d871e2b38356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
