# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536d75300ee5429571e2356a93bef2eed05c6b3434b0774e05851e294bd9e50571ddd05d6d8d6d06f7e764d93ae513dcade51c74cdba608456e27b63bdaf16eb

test:
  secret_key_base: cec2cb46e21d54cb12d7b4a605c31d804bd8c9ca9420ab51781164b9b74d8d9ef7a4b2f9d75eede58912355c7b726d2f7caa94c8ec10bf74aa8e3257a35214f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
