# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e038abe56a06f108ef23e510922ac16f1fb1bee83a00fab834b6270d393a9efe35d43fd335d5285b3b76d50fd52d1c7f88be72ed6aa80ed5a003fbeb6a1a0c

test:
  secret_key_base: 76a2fded24e80b573bcd4c536dcac7a6efdff29016a0baacf489273e1e1cb9d59d9e45a6db57d607c38a4cf59a33813a14de255db50636072d10133007fc44d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
